= NMEA0183 library for Arduino, Teensy and RPi =

# NMEA0183
NMEA0183 library for Arduino, Teensy and RPi

Object oriented NMEA0183 library for Arduino, Teensy and RPi

Library gives you a e.g. easy way to make NMEA0183->NMEA2000 interface like Actisense device.

Currently there are most common NMEA0183 messages parser/create function.

To compile example NMEA0183ToN2k or NMEA2000ToNMEA0183 you need also 
NMEA2000 library https://github.com/ttlappalainen/NMEA2000 and board dependent
driver libraries. See more on NMEA2000 library document.

*Note for Arduino DUE users!*

Currently code uses availableForWrite on writing serial. You have to modify next files and add availableForWrite to them. 
Note also that paths are version depended and here 1.6.11.

"C:\Users<your username>\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.11\cores\arduino\Print.h"
----
    virtual size_t write(uint8_t) = 0;
    virtual int availableForWrite(void) = 0;
    size_t write(const char *str) {
----
"C:\Users\lappalai\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.11\cores\arduino\HardwareSerial.h"
----
    virtual operator bool() = 0;
    virtual int availableForWrite(void)=0;
----


== License ==

Copyright (c) 2015-2019 Timo Lappalainen, Kave Oy, www.kave.fi

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
